deployment:
  tasks:
    - /usr/local/cpanel/3rdparty/bin/git pull origin develop
    - /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist
    - /bin/rsync -av --delete --exclude='.git' ./ /home/zerobiir/dev.zerobi.ir/
