---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zerobiir/dev.zerobi.ir/
    - /bin/rsync -rav --delete --exclude=.git --exclude=.cpanel.yml --exclude=sites/*/files --exclude=sites/*/public --exclude=sites/*/private --exclude=sites/*/files-public --exclude=sites/*/files-private --exclude=sites/*/translations --exclude=sites/*/tmp --exclude=sites/*/cache --exclude=sites/*/*settings*.php --exclude=sites/*/*services*.yml --exclude=.idea --exclude=.vscode --exclude=.DS_Store ./ $DEPLOYPATH/
    - cd $DEPLOYPATH && /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

